#Virtual Machine name
machine_name: vum-vagrant

#Guest timezone
timezone: Europe/Kiev

#Virtual Machine IP
ip: 192.168.10.2

#Virtual Machine CPU core number
cpus: 1

#Virtual Machine RAM
memory: 1024
